### ISSUE TITLE
Fulltext search.

### ISSUE THREAD

**Issue by j-pb** [arthurhsu/rdb#6]
One of the big selling points of WebSQL are the full-text search capabilities that it inherited form SQLite.
The RDB spec seems to include this use case through `MATCH` regex predicates. However there is no mentioning if this is actually efficient through a full-text index, or linear in the number of rows.

Any thoughts :)?

Cheers, JP

**Comment by arthurhsu** [comment]
I'm not sure if that's an existing feature for Microsoft SQL server compact.
match is something to replace SQL's LIKE statement, which I did expect a lot of inefficiencies.

**Comment by arthurhsu** [comment]
Extend match() predicate to take simple full-text search which is somewhat inline with SQLite FTS extension but hide the complexity of create virtual table inside engine. SQLServer and Oracle uses CONTAINS and bunch other extended syntax, which I don't think I want to put that in the already gigantic v1 spec.
